## Empty and Full array

In [7]:
import numpy as np

ar = np.array([1,2,3,4,5,6])
print("Array is:",ar)

# Empty array means uninitialised array with random values
em_arr = np.empty((3,4),dtype=int)
print(em_arr)

full_arr = np.full((3,3),55,dtype=int)
print(full_arr)

Array is: [1 2 3 4 5 6]
[[4128860 6029375 3801155 5570652]
 [6619251 7536754 6357084 7143524]
 [7209065 4259932 7340144 6357060]]
[[55 55 55]
 [55 55 55]
 [55 55 55]]


## Zeros

In [9]:
zer_ar = np.zeros((4,3),dtype=int)
print(zer_ar)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


## Ones

In [10]:
one_ar = np.ones((4,3),dtype=int)
print(one_ar)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


## Tolist (for checking whether certain rows exist or not)

In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print()
print([1,2,3] in arr.tolist())
print([3,4,5] in arr.tolist())
print([7,8,9] in arr.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

True
False
True


## Remove rows in numpy array that contains non-numeric values

In [14]:
n_arr = np.array([[10.5, 22.5, 3.8, 5], 
                  [23.45, 50, 78.7, 3.5], 
                  [41, np.nan, np.nan, 0], 
                  [20, 50.20, np.nan, 2.5], 
                  [18.8, 50.60, 8.8, 58.6]]) 
  
print("Given array:") 
print(n_arr) 
  
print("\nRemove all rows containing non-numeric elements") 
print(n_arr[~np.isnan(n_arr).any(axis=1)]) 

Given array:
[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [41.     nan   nan  0.  ]
 [20.   50.2    nan  2.5 ]
 [18.8  50.6   8.8  58.6 ]]

Remove all rows containing non-numeric elements
[[10.5  22.5   3.8   5.  ]
 [23.45 50.   78.7   3.5 ]
 [18.8  50.6   8.8  58.6 ]]


## Find number of occurences of a sequence in an array

In [22]:
arr1 = np.array([[2, 8, 9, 4],  
                   [9, 4, 9, 4], 
                   [4, 5, 9, 7], 
                   [2, 9, 4, 3]]) 
x = repr(arr1).count("9, 4")

print(x)

4


## Find most frequent value in a numpy array

In [31]:
arr2 = np.array([1,2,3,4,5,1,2,1,1,1])

# bincount() method of NumPy to get the count of occurrences of each element in the array
y = np.bincount(arr2).argmax()
print(y)

1


In [37]:
x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, 3]) 
print("Original array:") 
print(x) 
  
print("Most frequent value in above array") 
y = np.bincount(x) 
print("bincount value:",y)
maximum = max(y) 
print(maximum)

for i in range(len(y)): 
    if y[i] == maximum: 
        print(i, end=" ") 


Original array:
[1 1 1 2 3 4 2 4 3 3 3]
Most frequent value in above array
bincount value: [0 3 2 4 2]
4
3 

## Combining a oneD and twoD array