## Indexing

In [1]:
import numpy as np

var = np.array([0,9,7,6])
#               0,1,2,3
#              -4,-3,-2,-1

print(var[1])
print(var[-4])

9
0


In [4]:
var1 = np.array([[0,9,7],[4,5,6]])

print(var1)
print(var1.ndim)
print()

print(var1[0,2])

[[0 9 7]
 [4 5 6]]
2

7


In [5]:
var2 = np.array([[[2,3],[6,7]]])

print(var2)
print(var2.ndim)
print()
print(var2[0,1])

[[[2 3]
  [6 7]]]
3

[6 7]
