## Slicing

In [2]:
import numpy as np

var = np.array([1,2,3,4,5,6,7])

print(var)
print()
print("2 to 5: ",var[1:5])
print("2 to end: ",var[1:])
print("start to 5: ",var[:5])
print("stop: ",var[1:6:2])

[1 2 3 4 5 6 7]

2 to 5:  [2 3 4 5]
2 to end:  [2 3 4 5 6 7]
start to 5:  [1 2 3 4 5]
stop:  [2 4 6]


In [4]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var1)
print()
print("8 to 5:",var1[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5: [12 13 14 15]
