In [1]:
import numpy as np
var = np.array([[4,2,3],[1,11,2],[22,42,3]])
print(np.sort(var))

[[ 2  3  4]
 [ 1  2 11]
 [ 3 22 42]]


In [2]:
var1 = np.array(["a","r","s","o","u"])
print(np.sort(var1))

['a' 'o' 'r' 's' 'u']
