## Zeros

In [17]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print("\n")
print(ar_zero)

[0. 0. 0. 0.]


[0. 0. 0. 0.]


## Ones

In [18]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


## Empty

In [20]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


## Range

In [21]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


## Diagonal

In [22]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## Linspace

In [26]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
