# DataTypes

1. bool_ --> Boolean
2. int_ --> Integer
3. Intc --> Identical to C int(normally int32 or int64)
4. Intp --> Integer used for indexing
5. int8 --> Byte (-128 to 127)
6. int16 --> Integer (-32768 to 32767)
7. int32 --> Integer()
8. int64 --> Integer()
9. uint8 --> Unsigned integer (0to 255)
10. uint16 --> Unsigned integer()
11. uint32 --> Unsigned integer()
12. uint64 --> Unsigned integer()
13. float_ --> Float
14. float16 --> half precision float 
15. float32 --> single precision float
16. float64 --> double precision float
17. complex --> Shorthand for complex128
18. complex64 -->
19. complex128 -->

20. i --> integer
21. b --> boolean
22. u --> unsigned integer
23. f --> float
24. c --> complex float
25. m --> timedelta
26. M --> datetime
27. O --> object
28. S --> String
29. U --> Unicode string
30. V --> the fixed chunk of memory for other types(void)

In [1]:
import numpy as np

var = np.array([1,2,3,4,5,11,22,31,12])
print("Data type:",var.dtype)

Data type: int32


In [2]:
var = np.array([1.,2,3.,4])
print("Data type:",var.dtype)

Data type: float64


In [3]:
var = np.array(["A","B","C","D"])
print("Data type:",var.dtype)

Data type: <U1


In [4]:
var = np.array(["A","B","C","D",1,2,3])
print("Data type:",var.dtype)

Data type: <U11


## Datatype Conversions

In [6]:
x = np.array([1,2,3,4], dtype = np.int8)
print("Data Type:",x.dtype)
print(x)

Data Type: int8
[1 2 3 4]


In [7]:
x1 = np.array([1,2,3,4], dtype = "f")
print("Data Type:",x1.dtype)
print(x1)

Data Type: float32
[1. 2. 3. 4.]


In [9]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_one = np.int_(new)

print("Data type of x2 is:",x2.dtype)
print("Data type of new is:",new.dtype)
print("Data type of new_one is:",new_one.dtype)

print(x2)
print(new)
print(new_one)

Data type of x2 is: int32
Data type of new is: float32
Data type of new_one is: int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [ ]:
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)
print(x3)
print(new_1)