## Arithmetic Operations

1. a+b  --> np.add(a,b)
2. a-b  --> np.subtract(a,b)
3. a*b  --> np.multiply(a,b)
4. a/b  --> np.divide(a,b)
5. a%b  --> np.mod(a,b)
6. a**b --> np.power(a,b)
7. 1/a  --> np.reciprocal(a)

In [9]:
import numpy as np

var = np.array([1,2,3,4])
var_add = var+3
print(var_add)

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
sum = np.add(x,y)
print(sum)

[4 5 6 7]
[ 6  8 10 12]


In [2]:
var = np.array([1,2,3,4])
var_sub = var-1
print(var_sub)

[0 1 2 3]


In [4]:
var = np.array([1,2,3,4])
var_mult = var*3
print(var_mult)

[ 3  6  9 12]


In [5]:
var = np.array([1,2,3,4])
var_div = var/3
print(var_div)

[0.33333333 0.66666667 1.         1.33333333]


In [6]:
var = np.array([1,2,3,4])
var_mod = var%2
print(var_mod)

[1 0 1 0]


In [7]:
var = np.array([1,2,3,4])
var_pow = var**2
print(var_pow)

[ 1  4  9 16]


In [11]:
var = np.array([1,2,3,4])
var_rec = np.reciprocal(var)
print(var_rec)

[1 0 0 0]


## 2D Array

In [10]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

print(var21)
print()
print(var22)
print()
varAdd = var21+var22
print(varAdd)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


1. np.min(x)
2. np.max(x)
3. np.argmin(x)
4. np.sqrt(x)
5. np.sin(x)
6. np.cos(x)
7. np.cumsum(x) --> sum till particular elem (preprocessing of array)

In [19]:
arr = np.array([3,1,5,6,31,9])
print("Minimum is:",np.min(arr),",And place is:",np.argmin(arr)+1)
print("Maximum is:",np.max(arr),",And place is:",np.argmax(arr)+1)
print(np.sqrt(arr))

Minimum is: 1 ,And place is: 2
Maximum is: 31 ,And place is: 5
[1.73205081 1.         2.23606798 2.44948974 5.56776436 3.        ]


In [21]:
arr1 = np.array([[1,2,3],[9,5,6]])
## axis=0 (along column)  axis=1 (along row)
print(np.min(arr1,axis=0))

[1 2 3]


In [23]:
arr2 = np.array([1,2,3])
sin1 = np.sin(arr2)
print("Sin values of arr2 are:",sin1)
cos1 = np.cos(arr2)
print("Cos values of arr2 are:",cos1)
cumsum1 = np.cumsum(arr2)
print("Cumsum values of arr2 are:",cumsum1)

Sin values of arr2 are: [0.84147098 0.90929743 0.14112001]
Cos values of arr2 are: [ 0.54030231 -0.41614684 -0.9899925 ]
Cumsum values of arr2 are: [1 3 6]
